In [1]:
import kagglehub
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("asaniczka/tmdb-movies-dataset-2023-930k-movies")
df = pd.read_csv(f"{path}/TMDB_movie_dataset_v11.csv")
df = df.head(5000)
df.head(20)

Downloading from https://www.kaggle.com/api/v1/datasets/download/asaniczka/tmdb-movies-dataset-2023-930k-movies?dataset_version_number=535...

100%|██████████| 213M/213M [00:08<00:00, 27.2MB/s]

Extracting files...

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
5,293660,Deadpool,7.606,28894,Released,2016-02-09,783100000,108,False,/en971MEXui9diirXlogOrPKmsEn.jpg,...,Deadpool,The origin story of former Special Forces oper...,72.735,/zq8Cl3PNIDGU3iWNRoc5nEZ6pCe.jpg,Witness the beginning of a happy ending.,"Action, Adventure, Comedy","20th Century Fox, The Donners' Company, Genre ...",United States of America,English,"superhero, anti hero, mercenary, based on comi..."
6,299536,Avengers: Infinity War,8.255,27713,Released,2018-04-25,2052415039,149,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,...,Avengers: Infinity War,As the Avengers and their allies have continue...,154.340,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,An entire universe. Once and for all.,"Adventure, Action, Science Fiction",Marvel Studios,United States of America,"English, Xhosa","sacrifice, magic, superhero, based on comic, s..."
7,550,Fight Club,8.438,27238,Released,1999-10-15,100853753,139,False,/hZkgoQYus5vegHoetLkCJzb17zJ.jpg,...,Fight Club,A ticking-time-bomb insomniac and a slippery s...,69.498,/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg,Mischief. Mayhem. Soap.,Drama,"Regency Enterprises, Fox 2000 Pictures, Taurus...",United States of America,English,"dual identity, rage and hate, based on novel o..."
8,118340,Guardians of the Galaxy,7.906,26638,Released,2014-07-30,772776600,121,False,/uLtVbjvS1O7gXL8lUOwsFOH4man.jpg,...,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",33.255,/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg,All heroes start somewhere.,"Action, Science Fiction, Adventure",Marvel Studios,United States of America,English,"spacecraft, based on comic, space, orphan, adv..."
9,680,Pulp Fiction,8.488,25893,Released,1994-09-10,213900000,154,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,...,Pulp Fiction,"A burger-loving hit man, his philosophical par...",74.862,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,Just because you are a character doesn't mean ...,"Thriller, Crime","Miramax, A Band Apart, Jersey Films",United States of America,"English, Spanish, French","drug dealer, boxer, massage, stolen money, bri..."
10,13,Forrest Gump,8.477,25409,Released,1994-06-23,677387716,142,False,/qdIMHd4sEfJSckfVJfKQvisL02a.jpg,...,Forrest Gump,A man with a low IQ has accomplished great thi...,92.693,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,The world will never be the same once you've s...,"Comedy, Drama, Romance","Paramount, The Steve Tisch Company, Wendy Fine...",United States of America,English,"vietnam war, vietnam veteran, mentally disable..."
11,671,Harry Potter and the Philosopher's Stone,7.916,25379,Released,2001-11-16,976475550,152,False,/hziiv14OpD73u9gAak4XDDfBKa2.jpg,...,Harry Potter and the Philosopher's Stone,Harry Potter has lived under the stairs at his...,185.482,/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg,Let the magic begin.,"Adventure, Fantasy","Warner Bros. Pictures, Heyday Films, 1492 Pict...","United Kingdom, United States of America",English,"witch, school friend, friendship, london, engl..."
12,1726,Iron Man,7.640,24874,Released,2008-04-30,585174222,126,False,/cyecB7godJ6kNHGONFjUyVN9OX5.jpg,...,Iron Man,"After being held captive in an Afghan cave, bi...",72.897,/78lPtwv72eTNqFW9COBYI0dWDJa.jpg,Heroes aren't born. They're built.,"Action, Science Fiction, Adventure",Marvel Studios,United States of America,"English, Persian, Urdu, Arabic","middle east, superhero, arms dealer, malibu, b..."
13,68718,Django Unchained,8.171,24672,Released,2012-12-25,425368238,165,False,/5Lbm0gpFDRAPIV1Cth6ln9iL1ou.jpg,...,Django Unchained,"With the help of a German bounty hunter, a fre...",54.224,/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg,"Life, liberty and the pursuit of vengeance.","Drama, Western","The Weinstein Company, Columbia Pictures",United States of America,"English, French, German","rescue, friendship, bounty hunter, texas, slav..."
14,278,The Shawshank Redemption,8.702,24649,Released,1994-09-23,28341469,142,False,/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg,...,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,122.610,/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg,Fear can hold you prisoner. Hope can set you f...,"Drama, Crime",Castle Rock Entertainment,United States of America,English,"prison, friendship, police brutality, corrupti..."
15,299534,Avengers: Endgame,8.263,23857,Released,2019-04-24,2800000000,181,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,...,Avengers: Endgame,After the devastating events of Avengers: Infi...,91.756,/or06FN3Dka5tukK1e9sl16pB3iy.jpg,Avenge the fallen.,"Adventure, Science Fiction, Action",Marvel Studios,United States of America,"English, Japanese, Xhosa","superhero, time travel, space travel, time mac..."
16,603,The Matrix,8.206,23815,Released,1999-03-30,463517383,136,False,/oMsxZEvz9a708d49b6UdZK1KAo5.jpg,...,The Matrix,"Set in the 22nd century, The Matrix tells the ...",78.564,/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg,Welcome to the Real World.,"Action, Science Fiction","Village Roadshow Pictures, Groucho II Film Par...",United States of America,English,"man vs machine, martial arts, dream, artificia..."
17,597,Titanic,7.900,23637,Released,1997-11-18,2264162353,194,False,/rzdPqYx7Um4FUZeD8wpXqjAUcEm.jpg,...,Titanic,101-year-old Rose DeWitt Bukater tells the sto...,102.348,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,Nothing on Earth could come between them.,"Drama, Romance","Paramount, 20th Century Fox, Lightstorm Entert...",United States of America,"English, French, German, Swedish, Italian, Rus...","epic, ship, drowning, panic, shipwreck, evacua..."
18,475557,Joker,8.168,23425,Released,2019-10-01,1074458282,122,False,/hO7KbdvGOtDdeg0W4Y5nKEHeDDh.jpg,...,Joker,"During the 1980s, a failed stand-up comedian i...",54.522,/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg,Put on a happy face.,"Crime, Thriller, Drama","Warner Bros. Pictures, Joint Effort, Village R...","Canada, United States of America",English,"dream, street gang, society, psychopath, clown..."
19,120,The Lord of the Rings: The Fellowship of the Ring,8.402,23323,Released,2001-12-18,871368364,179,False,/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg,...,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",87.037,/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg,One ring to rule them all,"Adventure, Fantasy, Action","New Line Cinema, WingNut Films, The Saul Zaent...","New Zealand, United States of America",English,"based on novel or book, orcs, elves, dwarf, ma..."

In [2]:
# data cleaning remove redundunt columns
redundant_cols = ["id","vote_count","status","release_date","revenue","runtime","backdrop_path","budget","homepage","original_title","poster_path"]
df.drop(redundant_cols, axis=1, inplace=True)
df.head()

# first remove duplicates
df.drop_duplicates(inplace=True)

# drop columns having tite = null
df = df.dropna(subset=["title"])

# replace null overview to it's title
df = df.fillna({"overview": df["title"]})
df = df.fillna({"tagline": df["title"]})
df = df.dropna(subset=["genres"])
df = df.fillna({"production_countries": 'unitedstatesofamerica'})
df = df.fillna({"spoken_languages": 'English'})
df = df.fillna({"keywords": df["title"]})

# replace false with 0 and True with 1 in adult column
df["adult"] = df["adult"].astype(int)

df.head()

,title,vote_average,adult,imdb_id,original_language,overview,popularity,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,Inception,8.364,0,tt1375666,en,"Cobb, a skilled thief who commits corporate es...",83.952,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,Interstellar,8.417,0,tt0816692,en,The adventures of a group of explorers who mak...,140.241,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,The Dark Knight,8.512,0,tt0468569,en,Batman raises the stakes in his war on crime. ...,130.643,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,Avatar,7.573,0,tt0499549,en,"In the 22nd century, a paraplegic Marine is di...",79.932,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,The Avengers,7.710,0,tt0848228,en,When an unexpected enemy emerges and threatens...,98.082,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [3]:
import re

# convert string to list of string in spoken_languages and generes and keywords
# Function to clean and normalize categorical values
def clean_list_column(col_values):
    return [re.sub(r"[^a-zA-Z0-9\s-]", "", val).strip().lower() for val in col_values]

# Apply to all relevant columns
for col in ["spoken_languages", "genres", "keywords", "production_companies", "production_countries"]:
    df[col] = df[col].astype(str).apply(lambda x: x.split(",") if ',' in x else [x])
    df[col] = df[col].apply(clean_list_column)

In [4]:
from sklearn.preprocessing import MultiLabelBinarizer

def encode_top_n_categorical(df, column_name, top_n):
    """
    Converts a categorical column with multiple values per row into a one-hot encoded DataFrame.
    Keeps only the top N most frequent categories.

    Parameters:
    - df (pd.DataFrame): The input DataFrame.
    - column_name (str): The name of the categorical column to encode.
    - top_n (int): The number of top categories to keep.

    Returns:
    - pd.DataFrame: One-hot encoded DataFrame with only the top N categories.
    """
    mlb = MultiLabelBinarizer()

    # Perform MultiLabelBinarization
    encoded_df = pd.DataFrame(
        mlb.fit_transform(df[column_name]),
        columns=mlb.classes_,
        index=df.index
    )

    # Compute sum for each encoded column
    column_sums = encoded_df.sum(axis=0)

    # Get the top N most common columns
    top_columns = column_sums.nlargest(top_n).index
    encoded_df = encoded_df[top_columns]

    return encoded_df

# Apply encoding with top N selection
genre_encoded = encode_top_n_categorical(df, "genres", 10)
language_encoded = encode_top_n_categorical(df, "spoken_languages", 10)
keyword_encoded = encode_top_n_categorical(df, "keywords", 50)
production_company_encoded = encode_top_n_categorical(df, "production_companies", 20)
production_country_encoded = encode_top_n_categorical(df, "production_countries", 10)

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

def vectorize_text_column(df, column_name, max_features=500):
    """
    Converts a text column into a numerical matrix using TF-IDF.

    Parameters:
    - df (pd.DataFrame): The input DataFrame.
    - column_name (str): The name of the text column to vectorize.
    - max_features (int): The number of most important words to keep.

    Returns:
    - pd.DataFrame: A DataFrame where each column represents a word's importance in the text.
    """
    tfidf = TfidfVectorizer(max_features=max_features, stop_words="english")

    # Transform the text column into a TF-IDF matrix
    tfidf_matrix = tfidf.fit_transform(df[column_name].fillna(""))  # Fill NaN with empty string

    # Convert to DataFrame
    tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out(), index=df.index)

    return tfidf_df

overview_encoded = vectorize_text_column(df, "overview", max_features=500)
tagline_encoded = vectorize_text_column(df, "tagline", max_features=200)

In [6]:
# Concatenate all the feature matrices
final_feature_matrix = pd.concat([
    genre_encoded,
    language_encoded,
    keyword_encoded,
    production_company_encoded,
    production_country_encoded,
    overview_encoded,
    tagline_encoded
], axis=1)

final_feature_matrix.shape

(5000, 800)

In [7]:
final_df = pd.concat([df[['title']], final_feature_matrix,df[['imdb_id']]], axis=1)
final_df.head()

,title,drama,comedy,thriller,action,adventure,romance,crime,science fiction,horror,...,weapon,welcome,woman,won,world,worlds,wrong,year,years,imdb_id
0,Inception,0,0,0,1,1,0,0,1,0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,tt1375666
1,Interstellar,1,0,0,0,1,0,0,1,0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,tt0816692
2,The Dark Knight,1,0,1,1,0,0,1,0,0,...,0.0,0.607659,0.0,0.0,0.460148,0.0,0.0,0.0,0.0,tt0468569
3,Avatar,0,0,0,1,1,0,0,1,0,...,0.0,0.000000,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,tt0499549
4,The Avengers,0,0,0,1,1,0,0,1,0,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,tt0848228

In [8]:
# Save above generated data to csv file for better convience
final_df.to_csv("cleaned_data.csv",index=False)